- block:
  - name: INSTALL HTTPD SERVICE ON HOST1 
    package: 
      name: "{{ item }}"
      state: installed 
    with_items: 
      - httpd
    when: inventory_hostname == "aaloksinghvi2c.mylabserver.com" 

  - name: verify_install
    service:  
        name: "{{ item }}" 
        state: started 
        enabled: true 
    with_items:
      - httpd
    when: inventory_hostname == "aaloksinghvi2c.mylabserver.com"

- block:
  - name: INSTALL RABBITMQ SERVICE ON HOST2
    package: 
      name: "{{ item }}"
      state: installed 
    with_items: 
      - rabbitmq-server 
    when: inventory_hostname == "aaloksinghvi3c.mylabserver.com"

  - name: verify_install
    service:  
        name: "{{ item }}" 
        state: started 
        enabled: true 
    with_items:
      - rabbitmq-server
    when: inventory_hostname == "aaloksinghvi3c.mylabserver.com"

- block:
  - name: install repo for PostgreSQL 9.4
    yum:
      name: https://download.postgresql.org/pub/repos/yum/9.4/redhat/rhel-6-x86_64/pgdg-centos94-9.4-3.noarch.rpm
      state: present
    when: inventory_hostname == "aaloksinghvi4c.mylabserver.com"

  - name: INSTALL POSTGRESSQL SERVICE ON HOST3
    package: 
      name: "{{ item }}"
      state: installed 
    with_items:
      - gcc
      - openldap-devel
      - python-devel
      - readline-devel
      - openssl-devel
      - redhat-lsb
      - bison
      - flex
      - perl-ExtUtils-Embed
      - zlib-devel
      - crypto-utils
      - openssl-devel
      - pam-devel
      - libxml2-devel
      - libxslt-devel
      - tcl
      - tcl-devel
      - openssh-clients
      - bzip2
      - net-tools
      - wget
      - screen
      - ksh
    when: inventory_hostname == "aaloksinghvi4c.mylabserver.com"

  - name: verify_install
    service:
      name: "{{ item }}" 
      state: started 
      enabled: true
    with_items:
      - postgresql94-server
      - postgresql94-contrib
      - pg_repack94
    when: inventory_hostname == "aaloksinghvi4c.mylabserver.com"

 

